---
swagger: '2.0'
info:
  version: 1.0.0
  title: GeoServer Template
  description: Manage templates used to configure output (for example GetFeatureInfo reponse). Templates can be registered for the entire server or workspace. You can also configure a template for use with a store, featureType or coverage.

paths:
  /templates:
    get:
      operationId: templatesGet
      summary: List of templates for the server
      description: Displays a list of templates resitered for use on the server.
      produces:
        - text/html
        - application/xml
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Templates"
  /workspaces/{workspace}/templates:
    parameters:
      - $ref: "#/parameters/Workspace"  
    get:
      operationId: templatesWorkspaceGet
      summary: List of templates for workspace
      description: Displays a list of templates registered for use in a workspace (example for GetFeatureInfo WMS operation).
      produces:
        - text/html
        - application/xml
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Templates"
  /workspaces/{workspace}/datastores/{store}/templates:
    parameters:
      - $ref: "#/parameters/Workspace"
      - $ref: "#/parameters/Store"      
    get:
      operationId: templatesDataStoreGet
      summary: List of templates for a DataStore
      description: Displays a list of templates registered for use by all layers generated by a DataStore (example for GetFeatureInfo WMS operation).
      produces:
        - text/html
        - application/xml
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Templates"
  /workspaces/{workspace}/datastores/{store}/featuretypes/{type}/templates:
    parameters:
      - $ref: "#/parameters/Workspace"  
      - $ref: "#/parameters/Store"  
      - name: type
        in: path
        required: true
        type: string
        description: The feature type name      
    get:
      operationId: templatesDataStoreFTGet
      summary: List of templates for a DataStore
      description: Displays a list of templates registered for use by feature type (example for GetFeatureInfo WMS operation).
      produces:
        - text/html
        - application/xml
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Templates"
  /workspaces/{workspace}/coveragestore/{store}/templates:
    parameters:
      - $ref: "#/parameters/Workspace"
      - $ref: "#/parameters/Store"
    get:
      operationId: templatesDataStoreCSGet
      summary: List of templates for a DataStore
      description: Displays a list of templates registered for use by all layers generated by a Coverage Store (example for GetFeatureInfo WMS operation).
      produces:
        - text/html
        - application/xml
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Templates"
  /workspaces/{workspace}/coveragestore/{store}/coverages/{coverage}/templates:
    parameters:
      - $ref: "#/parameters/Workspace"
      - $ref: "#/parameters/Store"
      - name: coverage
        in: path
        required: true
        type: string
        description: The coverage name
    get:
      operationId: templatesCoverageGet
      summary: List of templates for a DataStore
      description: Displays a list of templates registered for use by a coverage (example for GetFeatureInfo WMS operation).
      produces:
        - text/html
        - application/xml
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Templates"

parameters:
  Workspace:
    name: workspace
    in: path
    required: true
    type: string
    description: The workspace name
  Store:
    name: store
    in: path
    required: true
    type: string
    description: The store name    

definitions:
  Templates:
    title: templates
    type: object
    properties:
      layerGroups:
        type: object
        
  TemplateReference:
    title: layers
    type: object
    properties:
      name:
        type: string
        description: Name of template
      link:
        type: string
        description: URL to template definition
